service: LabelBot

custom: ${file(./config.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

functions:
  LabelBot:
    handler: "handler.receiveWebhook"
    description: A Lambda function to label things on Home Assistant repositories
    memorySize: 128
    timeout: 10
    environment:
      STAGE: ${self:provider.stage}
      GITHUB_TOKEN: ${self:custom.github_token}
      GITHUB_SECRET: ${self:custom.github_secret}
    events:
      - http: POST github/webhook
